// Utilities to produce sample frames and convert frames to Arduino C arrays
import { mirrorX, mirrorY, rotateZ90 } from './drawHelpers.js';

export function framesToCArray(frames, name) {
  if (!frames || frames.length === 0) return '// no frames';

  // Apply mirroring transformations to match physical cube orientation
  const transformedFrames = frames.map((frame) => mirrorX(frame));

  const frameCount = transformedFrames.length;
  const cols = 64;
  let out = `// Generated by LED Cube Designer\n#define ${name}_FRAME_COUNT ${frameCount}\n\nconst byte ${name}[${frameCount}][${cols}] = {\n`;

  transformedFrames.forEach((f, fi) => {
    out += `  // Frame ${fi}\n  {`;
    for (let i = 0; i < cols; i++) {
      const v = f[i] || 0;
      out += '0x' + v.toString(16).toUpperCase().padStart(2, '0');
      if (i < cols - 1) out += ', ';
      if ((i + 1) % 8 === 0 && i < cols - 1) out += '\n   ';
    }
    out += '}';
    if (fi < frameCount - 1) out += ',\n\n';
    else out += '\n';
  });

  out += '};\n';
  return out;
}

export function generateHFile(name, frames) {
  const arr = framesToCArray(frames, name);
  const guard = `_${name}_H_`.toUpperCase();
  let out =
    `#ifndef ${guard}\n#define ${guard}\n\n#include <Arduino.h>\n\n` +
    arr +
    `\n#endif // ${guard}\n`;
  return out;
}

export function generateSketch(name, frames) {
  // generate the C array text first
  let arr = framesToCArray(frames, name);

  // replace the array declaration to place it in flash (PROGMEM)
  const header = `const byte ${name}[${frames.length}][64] = {`;
  const headerProg = `const byte ${name}[${frames.length}][64] PROGMEM = {`;
  arr = arr.replace(header, headerProg);

  // sketch template using PROGMEM and pgm_read_byte
  const sketch = `// Generated Arduino sketch for ${name}\n\n#include <Arduino.h>\n#include <avr/pgmspace.h>\n\n${arr}\n\n// send one frame stored in PROGMEM (framePtr points to 64 bytes)\nvoid sendFrameFromPROGMEM(const uint8_t *framePtr) {\n  Serial.write(0xF2);\n  for (int i = 0; i < 64; i++) {\n    uint8_t b = pgm_read_byte(framePtr + i);\n    Serial.write(b);\n  }\n}\n\nvoid setup(){\n  Serial.begin(38400);\n  delay(500);\n  // send open command\n  for(int i=0;i<70;i++) Serial.write(0xAD);\n  delay(200);\n}\n\nvoid loop(){\n  for (int f = 0; f < ${name}_FRAME_COUNT; f++) {\n    const uint8_t *framePtr = ${name}[f];\n    sendFrameFromPROGMEM(framePtr);\n    delay(200);\n  }\n  // keep looping\n}\n`;

  return sketch;
}

// This board's cube has its own onboard controller that does the real LED
// driving in its own firmware -- it isn't wired to Arduino GPIO pins at all.
// It speaks a fixed protocol (0xAD open handshake, then 0xF2 + 64 raw bytes
// per frame, repeated forever) directly over the same serial line the
// Arduino uses to talk to your PC. The exported ANIM.ino confirms this: its
// loop() only ever calls Serial.write() -- it never touches a pin.
//
// That means the Arduino's job here is just to relay bytes from USB
// straight through to the cube controller, verbatim, in real time. No
// parsing, no checksum, no ACK/NACK -- the previous version of this sketch
// implemented a request/confirm protocol the cube controller was never
// going to speak, which is why it silently did nothing no matter what was
// sent to it.
export function generateStreamingReceiverSketch() {
  const sketch = `// Live relay sketch for LED Cube
//
// This board's cube has its own onboard controller that does the actual
// LED driving -- this sketch does not touch any pins for LEDs. It just
// forwards every byte it receives over USB straight out its hardware
// Serial line to that controller, unmodified, in real time.
//
// Flash this and leave the board connected. On the website, click Connect,
// then use the Playback bar's Stream controls (not a one-shot Send) --
// this cube's controller falls back to its own built-in demo pattern
// whenever the live feed stops, so the site streams frames in a
// continuous loop for as long as you leave streaming on, the same way the
// exported ANIM.ino does.

#include <Arduino.h>

void setup() {
  Serial.begin(38400);
}

void loop() {
  if (Serial.available() > 0) {
    Serial.write(Serial.read());
  }
}
`;

  return sketch;
}

export function generateESP32Sketch(name, frames) {
  let arr = framesToCArray(frames, name);
  const header = `const byte ${name}[${frames.length}][64] = {`;
  const headerProg = `const byte ${name}[${frames.length}][64] PROGMEM = {`;
  arr = arr.replace(header, headerProg);

  return `// Generated ESP32 sketch for ${name}
// Flashes animation into ESP32 flash memory (PROGMEM)
//
// Cube data goes out Serial2's hardware UART (TX2 = GPIO17, RX2 = GPIO16 on
// most boards) through a level shifter to the cube's data pin -- NOT the
// USB port. Serial (USB) and Serial2 (TX2/RX2) are separate hardware
// UARTs; writing to Serial here would never reach a cube wired to TX2.

#include <Arduino.h>
#include <pgmspace.h>

${arr}

// Send one frame stored in PROGMEM (framePtr points to 64 bytes)
void sendFrameFromPROGMEM(const uint8_t *framePtr) {
  Serial2.write(0xF2);
  for (int i = 0; i < 64; i++) {
    uint8_t b = pgm_read_byte(framePtr + i);
    Serial2.write(b);
  }
}

void setup() {
  // Initialize Hardware Serial2 for Cube connection at 38400 baud
  Serial2.begin(38400, SERIAL_8N1, 16, 17);
  delay(500);
  // Send open command handshake (0xAD)
  for (int i = 0; i < 70; i++) {
    Serial2.write(0xAD);
  }
  delay(200);
}

void loop() {
  for (int f = 0; f < ${name}_FRAME_COUNT; f++) {
    const uint8_t *framePtr = ${name}[f];
    sendFrameFromPROGMEM(framePtr);
    delay(200);
  }
}
`;
}

export function generateESP32LiveRelaySketch() {
  return `// Live Relay Sketch for ESP32 (USB WebSerial to LED Cube)
//
// Relays bytes received over USB Serial (the WebSerial connection to the
// website) straight out Serial2's hardware UART (TX2 = GPIO17, RX2 = GPIO16
// on most boards) to the LED Cube controller, for real-time 8x8x8 LED cube
// frame streaming.
//
// IMPORTANT: the cube's data pin must be wired to TX2 (through a level
// shifter to 5V, with a shared GND) -- NOT to the USB port. Serial (USB)
// and Serial2 (TX2/RX2) are separate hardware UARTs on the ESP32; bytes
// written to Serial only go back out the USB cable, they never reach TX2.

#include <Arduino.h>

void setup() {
  Serial.begin(38400);
  Serial2.begin(38400, SERIAL_8N1, 16, 17); // RX2=GPIO16, TX2=GPIO17
}

void loop() {
  if (Serial.available() > 0) {
    uint8_t b = Serial.read();
    Serial2.write(b);
  }
}
`;
}

export function generateESP32WebAppSketch() {
  return `// ESP32 Self-Hosted Web App Sketch for LED Cube
//
// HOW IT WORKS — no config required:
//   1. Install libraries (see below) and flash this sketch.
//   2. Upload the website files to LittleFS (see step 5 below).
//   3. On first boot the ESP32 creates a hotspot called "LED Cube Setup".
//   4. Connect any phone/laptop to that hotspot — a captive portal opens.
//   5. Enter your home Wi-Fi password. The ESP32 saves it and reboots.
//   6. It connects to your network and serves the full designer app at
//      http://ledcube.local — no internet required.
//   7. Open ledcube.local in your browser. The app detects the .local
//      hostname and auto-switches to Dual Mode (Library tab appears,
//      Connect Serial is hidden). Design and push animations directly.
//
// To reset Wi-Fi credentials, hold GPIO0 low for 3 seconds on boot.
//
// DUAL MODE PROTOCOL (handled automatically by the app):
//   Byte 0 = command:  0x01 live stream | 0x02 save Slot 1 | 0x03 save Slot 2
//   Bytes 1+ = packed frames, 64 bytes each
//
// SETUP (one-time):
//   1. Libraries needed (Arduino Library Manager):
//        - WiFiManager by tzapu
//        - ESPAsyncWebServer + AsyncTCP
//        - WebSockets by Markus Sattler
//        - ESPmDNS (built in to ESP32 Arduino core)
//   2. Click "Download Website Files" on the Export tab to get the data/ zip.
//   3. Extract the zip into a folder called "data" next to this .ino file.
//   4. Tools -> ESP32 Sketch Data Upload to flash the data/ folder to LittleFS.
//      (Install the upload tool from: https://github.com/me-no-dev/arduino-esp32fs-plugin)
//   5. Tools -> Partition Scheme: pick "Default 4MB with spiffs" or any
//      scheme with at least 1 MB for LittleFS.
//   6. Flash this sketch (Upload button).

#include <WiFi.h>
#include <WiFiManager.h>
#include <WebSocketsServer.h>
#include <ESPAsyncWebServer.h>
#include <ESPmDNS.h>
#include <LittleFS.h>
${DUAL_MODE_HANDLER_C}

#define MDNS_HOSTNAME "ledcube"
#define RESET_PIN     0

AsyncWebServer  server(80);
WebSocketsServer webSocket(81);

void webSocketEvent(uint8_t num, WStype_t type, uint8_t* payload, size_t length) {
  if (type == WStype_BIN) {
    handleDualModeMessage(payload, length);
  } else if (type == WStype_TEXT) {
    if (length >= 4 && payload[0] == 'P' && payload[1] == 'I' && payload[2] == 'N' && payload[3] == 'G') {
      webSocket.sendTXT(num, "PONG");
    }
  }
}

void setup() {
  Serial.begin(38400);
  Serial2.begin(38400, SERIAL_8N1, 16, 17);

  // Send the open-communication handshake once at boot -- the cube ignores
  // 0xF2 frame packets until it has received this, so playback (including
  // slots auto-loaded from LittleFS below) would otherwise silently do nothing.
  for (int i = 0; i < 70; i++) Serial2.write(0xAD);
  delay(200);

  if (!LittleFS.begin(true)) {
    Serial.println("LittleFS mount failed — did you upload the data/ folder? See setup step 4.");
    return;
  }

  // Hold RESET_PIN low 3 s to wipe Wi-Fi credentials
  pinMode(RESET_PIN, INPUT_PULLUP);
  delay(100);
  if (digitalRead(RESET_PIN) == LOW) {
    unsigned long t = millis();
    while (digitalRead(RESET_PIN) == LOW && millis() - t < 3000) delay(50);
    if (millis() - t >= 3000) {
      WiFiManager wm;
      wm.resetSettings();
      Serial.println("Wi-Fi credentials wiped — rebooting into setup portal...");
      delay(500);
      ESP.restart();
    }
  }

  loadSlotsFromStorage();

  WiFiManager wm;
  wm.setConfigPortalTimeout(180);
  if (!wm.autoConnect("LED Cube Setup")) {
    Serial.println("Setup portal timed out — rebooting...");
    ESP.restart();
  }

  Serial.print("Connected! Open http://" MDNS_HOSTNAME ".local in your browser. IP: ");
  Serial.println(WiFi.localIP());

  if (MDNS.begin(MDNS_HOSTNAME)) {
    MDNS.addService("http", "tcp", 80);
    MDNS.addService("ws",   "tcp", 81);
  }

  server.serveStatic("/", LittleFS, "/").setDefaultFile("index.html");
  server.begin();

  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
}

void loop() {
  webSocket.loop();
  playNextFrame();
}
`;
}

// ---------------------------------------------------------------------------
// Shared C++ logic inserted into every Wi-Fi sketch that understands the
// Dual Mode binary protocol sent by sendFrames() in App.jsx:
//
//   Byte 0  : command flag
//               0x01 = live stream  -- play the payload frames in a loop
//               0x02 = save Slot 1  -- persist to LittleFS, play on next boot
//               0x03 = save Slot 2  -- same, second slot
//   Bytes 1+ : packed frame data, 64 bytes per frame (one byte per column,
//              each byte encodes the 8 Z-layer bits for that column).
//              Total length = 1 + (frameCount * 64).
//
// The slot data is stored as a file on LittleFS (/slot1.bin, /slot2.bin) so
// it survives power cycles. LittleFS shares the same multi-hundred-KB to
// multi-MB flash partition as the website files, so long scrolling-text
// animations (which need many frames to scroll the full message across the
// display) have plenty of room -- unlike NVS (ESP32 Preferences), whose
// default partition is only ~20 KB total and would silently fail to save
// once the frame data grew past that.
// On boot, if no live-stream has arrived yet, the last saved slot plays.
// ---------------------------------------------------------------------------
const DUAL_MODE_HANDLER_C = `
#include <LittleFS.h>

#define CMD_STREAM  0x01
#define CMD_SLOT1   0x02
#define CMD_SLOT2   0x03
#define FRAME_BYTES 64
#define MAX_FRAMES  4096  // 4096 * 64 = 256 KB -- LittleFS has room; heap is the real ceiling now

// Live-stream buffer (heap allocated, replaced on each CMD_STREAM message)
uint8_t* liveFrames    = nullptr;
int      liveFrameCount = 0;
int      liveFrameIdx   = 0;
bool     liveMode       = false;

// Slot buffers (loaded from LittleFS on boot, replaced by CMD_SLOT1/2 messages)
uint8_t* slot1Frames    = nullptr;
int      slot1FrameCount = 0;
uint8_t* slot2Frames    = nullptr;
int      slot2FrameCount = 0;

// Which slot is actively playing when not in live mode
int activeSlot = 1;
int slotFrameIdx = 0;

// ---- LittleFS slot storage helpers ------------------------------------------
//
// Each slot is a single file: a 4-byte little-endian frame count, followed
// by frameCount * FRAME_BYTES of raw frame data. Using files instead of NVS
// (Preferences) removes the ~20 KB NVS partition ceiling -- LittleFS shares
// the much larger flash partition already used for the website files, so
// long scrolling-text animations (many frames) save reliably.

void slotFilePath(int slot, char* out, size_t outLen) {
  snprintf(out, outLen, "/slot%d.bin", slot);
}

void saveSlotToFile(int slot, const uint8_t* data, int frameCount) {
  char path[16];
  slotFilePath(slot, path, sizeof(path));
  File f = LittleFS.open(path, "w");
  if (!f) { Serial.printf("Failed to open %s for writing\\n", path); return; }
  uint32_t fc = (uint32_t)frameCount;
  f.write((const uint8_t*)&fc, sizeof(fc));
  f.write(data, (size_t)frameCount * FRAME_BYTES);
  f.close();
}

uint8_t* loadSlotFromFile(int slot, int* outFrameCount) {
  char path[16];
  slotFilePath(slot, path, sizeof(path));
  *outFrameCount = 0;
  if (!LittleFS.exists(path)) return nullptr;
  File f = LittleFS.open(path, "r");
  if (!f) return nullptr;
  uint32_t fc = 0;
  if (f.read((uint8_t*)&fc, sizeof(fc)) != sizeof(fc) || fc == 0 || fc > MAX_FRAMES) {
    f.close();
    return nullptr;
  }
  uint8_t* buf = (uint8_t*)malloc((size_t)fc * FRAME_BYTES);
  if (!buf) { f.close(); return nullptr; }
  f.read(buf, (size_t)fc * FRAME_BYTES);
  f.close();
  *outFrameCount = (int)fc;
  return buf;
}

// ---- Incoming WebSocket binary message handler -----------------------------

void handleDualModeMessage(uint8_t* payload, size_t length) {
  if (length < 1) return;
  uint8_t cmd = payload[0];
  size_t  dataLen = length - 1;
  uint8_t* data   = payload + 1;

  int frameCount = (int)(dataLen / FRAME_BYTES);
  if (frameCount < 1) return;

  uint8_t* buf = (uint8_t*)malloc((size_t)frameCount * FRAME_BYTES);
  if (!buf) return;
  memcpy(buf, data, (size_t)frameCount * FRAME_BYTES);

  if (cmd == CMD_STREAM) {
    free(liveFrames);
    liveFrames     = buf;
    liveFrameCount = frameCount;
    liveFrameIdx   = 0;
    liveMode       = true;
    Serial.printf("Live stream: %d frame(s)\\n", frameCount);
  } else if (cmd == CMD_SLOT1) {
    free(slot1Frames);
    slot1Frames     = buf;
    slot1FrameCount = frameCount;
    activeSlot      = 1;
    slotFrameIdx    = 0;
    liveMode        = false;
    saveSlotToFile(1, buf, frameCount);
    Serial.printf("Saved %d frame(s) to Slot 1\\n", frameCount);
  } else if (cmd == CMD_SLOT2) {
    free(slot2Frames);
    slot2Frames     = buf;
    slot2FrameCount = frameCount;
    activeSlot      = 2;
    slotFrameIdx    = 0;
    liveMode        = false;
    saveSlotToFile(2, buf, frameCount);
    Serial.printf("Saved %d frame(s) to Slot 2\\n", frameCount);
  } else {
    free(buf); // unknown command
  }
}

// ---- Frame playback (call from loop()) -------------------------------------
//
// frameDelayMs: how long to hold each frame (mirrors the website's Delay
// slider -- 300 ms is the default). The website does NOT send timing yet;
// adjust this constant to taste or add it to the protocol later.

#define FRAME_DELAY_MS 300

unsigned long lastFrameTime = 0;

void playNextFrame() {
  unsigned long now = millis();
  if (now - lastFrameTime < FRAME_DELAY_MS) return;
  lastFrameTime = now;

  uint8_t* src   = nullptr;
  int      count = 0;
  int*     idx   = nullptr;

  if (liveMode && liveFrames && liveFrameCount > 0) {
    src   = liveFrames;
    count = liveFrameCount;
    idx   = &liveFrameIdx;
  } else if (activeSlot == 1 && slot1Frames && slot1FrameCount > 0) {
    src   = slot1Frames;
    count = slot1FrameCount;
    idx   = &slotFrameIdx;
  } else if (activeSlot == 2 && slot2Frames && slot2FrameCount > 0) {
    src   = slot2Frames;
    count = slot2FrameCount;
    idx   = &slotFrameIdx;
  } else {
    return; // nothing loaded yet
  }

  uint8_t* frame = src + (*idx) * FRAME_BYTES;

  // Send as a 65-byte packet: 0xF2 header + 64 column bytes
  uint8_t buf[65];
  buf[0] = 0xF2;
  memcpy(buf + 1, frame, FRAME_BYTES);
  Serial2.write(buf, 65);

  *idx = (*idx + 1) % count;
}

void loadSlotsFromStorage() {
  slot1Frames = loadSlotFromFile(1, &slot1FrameCount);
  if (slot1FrameCount > 0) Serial.printf("Slot 1 loaded: %d frame(s)\\n", slot1FrameCount);
  slot2Frames = loadSlotFromFile(2, &slot2FrameCount);
  if (slot2FrameCount > 0) Serial.printf("Slot 2 loaded: %d frame(s)\\n", slot2FrameCount);
}
`;

export function generateESP32WiFiRelaySketch() {
  return `// ESP32 Wireless Wi-Fi Relay Sketch for LED Cube
//
// HOW IT WORKS — no config required:
//   1. Flash this sketch.
//   2. On first boot the ESP32 creates a hotspot called "LED Cube Setup".
//   3. Connect any phone/laptop to that hotspot — a captive portal opens.
//   4. Enter your home Wi-Fi password. The ESP32 saves it and reboots.
//   5. It connects to your network and is reachable at http://ledcube.local
//   6. Open ledcube.local in your browser — the app detects the .local
//      hostname and automatically switches to Dual Mode (Library tab).
//
// To reset Wi-Fi credentials, hold GPIO0 low for 3 seconds on boot.
//
// DUAL MODE PROTOCOL (handled automatically by the app):
//   Byte 0 = command:  0x01 live stream | 0x02 save Slot 1 | 0x03 save Slot 2
//   Bytes 1+ = packed frames, 64 bytes each
//
// Libraries needed (Arduino Library Manager):
//   - WiFiManager by tzapu
//   - WebSockets by Markus Sattler
//   - ESPmDNS (built in to the ESP32 Arduino core)

#include <WiFi.h>
#include <WiFiManager.h>
#include <WebSocketsServer.h>
#include <ESPmDNS.h>
#include <LittleFS.h>
${DUAL_MODE_HANDLER_C}

#define MDNS_HOSTNAME "ledcube"
#define RESET_PIN     0   // GPIO0 (BOOT button on most boards) — hold 3s to wipe credentials

WebSocketsServer webSocket(81);

void webSocketEvent(uint8_t num, WStype_t type, uint8_t* payload, size_t length) {
  if (type == WStype_BIN) {
    handleDualModeMessage(payload, length);
  } else if (type == WStype_TEXT) {
    if (length >= 4 && payload[0] == 'P' && payload[1] == 'I' && payload[2] == 'N' && payload[3] == 'G') {
      webSocket.sendTXT(num, "PONG");
    }
  }
}

void setup() {
  Serial.begin(38400);
  // Cube data goes out Serial2's hardware UART (TX2 = GPIO17, RX2 = GPIO16
  // on most boards) through a level shifter to the cube's data pin.
  Serial2.begin(38400, SERIAL_8N1, 16, 17);

  if (!LittleFS.begin(true)) {
    Serial.println("LittleFS mount failed — saved slots will not persist.");
  }

  // Hold RESET_PIN low for 3 s on boot to wipe saved Wi-Fi credentials
  pinMode(RESET_PIN, INPUT_PULLUP);
  delay(100);
  if (digitalRead(RESET_PIN) == LOW) {
    unsigned long t = millis();
    while (digitalRead(RESET_PIN) == LOW && millis() - t < 3000) delay(50);
    if (millis() - t >= 3000) {
      WiFiManager wm;
      wm.resetSettings();
      Serial.println("Wi-Fi credentials wiped — rebooting into setup portal...");
      delay(500);
      ESP.restart();
    }
  }

  loadSlotsFromStorage();

  // Auto-connect or launch setup portal if credentials are missing/wrong
  WiFiManager wm;
  wm.setConfigPortalTimeout(180); // give up after 3 min and reboot
  if (!wm.autoConnect("LED Cube Setup")) {
    Serial.println("Setup portal timed out — rebooting...");
    ESP.restart();
  }

  Serial.print("Connected! IP: ");
  Serial.println(WiFi.localIP());

  if (MDNS.begin(MDNS_HOSTNAME)) {
    Serial.println("mDNS started — open http://" MDNS_HOSTNAME ".local in your browser");
    MDNS.addService("http", "tcp", 80);
    MDNS.addService("ws",   "tcp", 81);
  }

  webSocket.begin();
  webSocket.onEvent(webSocketEvent);
  Serial.println("WebSocket server ready on port 81");
}

void loop() {
  webSocket.loop();
  playNextFrame();
}
`;
}

// Plain-text wiring & troubleshooting guide, downloadable straight from the
// live site -- so anyone who lands here without ever visiting the GitHub
// repo (e.g. shared a link, found it some other way) still gets the full
// hardware setup and the fixes for the gotchas that came up building this:
// the ESP32's two separate UARTs, and breadboard power-rail splits.
export function generateWiringGuide() {
  return `LED CUBE DESIGNER -- ESP32 WIRING & TROUBLESHOOTING GUIDE
============================================================

This guide covers wiring an ESP32 to an 8x8x8 LED cube that has its own
onboard driver controller (the kind of cube where a 4-pin connector runs
to the cube, and the cube does its own LED multiplexing in firmware you
don't touch). If your cube is instead pin-driven directly by the
microcontroller (shift registers, bit-banged rows/columns), this guide
does not apply -- you need different sketches entirely.

------------------------------------------------------------
1. WHY YOU NEED A LEVEL SHIFTER
------------------------------------------------------------
The ESP32 runs its logic at 3.3V. Many of these cube controllers expect a
full 5V logic signal on their data-in pin. Wiring the ESP32 straight to
the cube can be unreliable or not work at all -- use a 5V level shifter,
for example an SN74AHCT125N (a common, cheap, non-inverting buffer chip).

------------------------------------------------------------
2. THE CUBE'S CONNECTOR
------------------------------------------------------------
Check your cube's own manual/photos for the exact pinout, but on this
style of cube, the 4-pin connector typically only needs 2 of its 4 pins:
  - Far-left pin  = data in (from the level shifter's output)
  - Far-right pin = GND
The middle two pins are commonly unused for this style of board.

The cube also needs its own separate power adapter running at the same
time as the ESP32 -- the 4-pin connector is signal/ground only, it does
not power the cube.

------------------------------------------------------------
3. MASTER WIRING MAP (ESP32 + SN74AHCT125N level shifter + cube)
------------------------------------------------------------
Power & Ground:
  ESP32 GND              -> Breadboard Ground Rail
  SN74AHCT125N Pin 7 (GND)   -> Breadboard Ground Rail
  SN74AHCT125N Pin 1 (1OE)   -> Breadboard Ground Rail (forces output enabled;
                                 this pin is active-LOW enable)
  ESP32 VIN (5V)         -> SN74AHCT125N Pin 14 (VCC)

Data path (3.3V in, 5V out):
  ESP32 TX2 (GPIO17)     -> SN74AHCT125N Pin 2 (1A)
  SN74AHCT125N Pin 3 (1Y)    -> Cube's far-left pin (data in)

Completing the circuit:
  Breadboard Ground Rail -> Cube's far-right pin (GND)

------------------------------------------------------------
4. TWO GOTCHAS THAT CAUSE "NOTHING HAPPENS, CUBE SHOWS ITS OWN
   FACTORY DEMO PATTERN" -- CHECK THESE FIRST
------------------------------------------------------------

A) The ESP32 has TWO separate hardware UARTs -- don't mix them up.
   "Serial" is the USB port (used for Wi-Fi status messages / talking to
   your PC). "Serial2" is the separate hardware UART on TX2 (GPIO17) /
   RX2 (GPIO16) that actually drives the cube through the level shifter.
   All the sketches this site generates already send cube frame data out
   Serial2 and keep Serial for USB debug only -- if you're hand-editing a
   sketch, make sure any code that talks to the cube writes to Serial2,
   not Serial. A telltale symptom of this mistake: the Arduino IDE's
   Serial Monitor shows garbled/binary-looking characters mixed into the
   text -- that's cube frame data being sent to the wrong UART.

B) Breadboard power rails are usually NOT bridged top-to-bottom.
   Most full-size breadboards have the top rail strip and the bottom rail
   strip as two electrically SEPARATE strips -- plugging into both and
   assuming they're the same net is a very easy mistake to make. If the
   ESP32's GND ends up on one rail while the level shifter's GND (pin 7)
   or the cube's GND wire ends up on the other, you can get inconsistent
   behavior even though each individual wire looks fine, and simple
   continuity/voltage checks near the chip can look "correct" without
   catching it. Fix: run one jumper wire directly bridging the top and
   bottom ground rails, or better, plug every ground wire (ESP32 GND,
   level shifter pin 1 + pin 7, and the cube's GND pin) into the exact
   same rail strip.

------------------------------------------------------------
5. STEP-BY-STEP DIAGNOSIS IF THE CUBE STILL WON'T RESPOND
------------------------------------------------------------
1. Confirm data is reaching the ESP32 at all: add a temporary Serial.print
   byte counter inside your WebSocket/relay handler to confirm bytes are
   arriving from the website before you worry about anything downstream.
2. Confirm the ESP32 is actually sending on Serial2/TX2: with a multimeter
   in DC voltage mode, measure the level shifter's input pin (1A, pin 2)
   against GND while streaming -- a UART actively sending data will show
   the voltage flickering/jumping, not sitting at a steady clean value.
3. Confirm the level shifter's output reaches the cube: same flicker test
   on the output pin (1Y, pin 3).
4. Confirm power and enable to the chip: VCC (pin 14) to GND (pin 7)
   should read about 5V; OE (pin 1) to GND should read about 0V.
5. If everything above checks out but the cube still shows its own
   factory demo pattern, re-check every ground connection is on the exact
   same rail (see gotcha B above) -- this is the single most common
   remaining cause.

------------------------------------------------------------
6. SERIAL PROTOCOL REFERENCE (for the curious / for custom sketches)
------------------------------------------------------------
38,400 baud, 8N1.
  - Handshake: 70 repeated 0xAD bytes, sent once when streaming begins.
  - Each frame: one 0xF2 header byte, then 64 raw data bytes (one byte per
    cube column; bit 0/LSB = bottom layer, bit 7/MSB = top layer).
  - Frames repeat continuously for as long as you're streaming. If the
    stream stops, the cube's own controller falls back to its built-in
    demo pattern automatically -- this is normal, not an error.
`;
}

// ========== TEXT & GLYPH ANIMATION ==========

// Simple 5x7 font (columns, LSB = top row)
const FONT5x7 = {
  ' ': [0x00, 0x00, 0x00, 0x00, 0x00],
  A: [0x7c, 0x12, 0x11, 0x12, 0x7c],
  B: [0x7f, 0x49, 0x49, 0x49, 0x36],
  C: [0x3e, 0x41, 0x41, 0x41, 0x22],
  D: [0x7f, 0x41, 0x41, 0x22, 0x1c],
  E: [0x7f, 0x49, 0x49, 0x49, 0x41],
  F: [0x7f, 0x09, 0x09, 0x09, 0x01],
  G: [0x3e, 0x41, 0x49, 0x49, 0x7a],
  H: [0x7f, 0x08, 0x08, 0x08, 0x7f],
  I: [0x00, 0x41, 0x7f, 0x41, 0x00],
  J: [0x20, 0x40, 0x41, 0x3f, 0x01],
  K: [0x7f, 0x08, 0x14, 0x22, 0x41],
  L: [0x7f, 0x40, 0x40, 0x40, 0x40],
  M: [0x7f, 0x02, 0x04, 0x02, 0x7f],
  N: [0x7f, 0x04, 0x08, 0x10, 0x7f],
  O: [0x3e, 0x41, 0x41, 0x41, 0x3e],
  P: [0x7f, 0x09, 0x09, 0x09, 0x06],
  Q: [0x3e, 0x41, 0x51, 0x21, 0x5e],
  R: [0x7f, 0x09, 0x19, 0x29, 0x46],
  S: [0x46, 0x49, 0x49, 0x49, 0x31],
  T: [0x01, 0x01, 0x7f, 0x01, 0x01],
  U: [0x3f, 0x40, 0x40, 0x40, 0x3f],
  V: [0x1f, 0x20, 0x40, 0x20, 0x1f],
  W: [0x7f, 0x20, 0x18, 0x20, 0x7f],
  X: [0x63, 0x14, 0x08, 0x14, 0x63],
  Y: [0x03, 0x04, 0x78, 0x04, 0x03],
  Z: [0x61, 0x51, 0x49, 0x45, 0x43],
  a: [0x20, 0x54, 0x54, 0x54, 0x78],
  b: [0x7f, 0x48, 0x44, 0x44, 0x38],
  c: [0x38, 0x44, 0x44, 0x44, 0x20],
  d: [0x38, 0x44, 0x44, 0x48, 0x7f],
  e: [0x38, 0x54, 0x54, 0x54, 0x18],
  f: [0x08, 0x7e, 0x09, 0x01, 0x02],
  g: [0x18, 0xa4, 0xa4, 0xa4, 0x7c],
  h: [0x7f, 0x08, 0x04, 0x04, 0x78],
  i: [0x00, 0x44, 0x7d, 0x40, 0x00],
  j: [0x20, 0x40, 0x44, 0x3d, 0x00],
  k: [0x7f, 0x10, 0x28, 0x44, 0x00],
  l: [0x00, 0x41, 0x7f, 0x40, 0x00],
  m: [0x7c, 0x04, 0x18, 0x04, 0x78],
  n: [0x7c, 0x08, 0x04, 0x04, 0x78],
  o: [0x38, 0x44, 0x44, 0x44, 0x38],
  p: [0xfc, 0x24, 0x24, 0x24, 0x18],
  q: [0x18, 0x24, 0x24, 0x18, 0xfc],
  r: [0x7c, 0x08, 0x04, 0x04, 0x08],
  s: [0x48, 0x54, 0x54, 0x54, 0x20],
  t: [0x04, 0x3f, 0x44, 0x40, 0x20],
  u: [0x3c, 0x40, 0x40, 0x20, 0x7c],
  v: [0x1c, 0x20, 0x40, 0x20, 0x1c],
  w: [0x3c, 0x40, 0x30, 0x40, 0x3c],
  x: [0x44, 0x28, 0x10, 0x28, 0x44],
  y: [0x1c, 0xa0, 0xa0, 0xa0, 0x7c],
  z: [0x44, 0x64, 0x54, 0x4c, 0x44],
  0: [0x3e, 0x45, 0x49, 0x51, 0x3e],
  1: [0x00, 0x21, 0x7f, 0x01, 0x00],
  2: [0x23, 0x45, 0x49, 0x49, 0x31],
  3: [0x22, 0x41, 0x49, 0x49, 0x36],
  4: [0x0c, 0x14, 0x24, 0x7f, 0x04],
  5: [0x72, 0x51, 0x51, 0x51, 0x4e],
  6: [0x3e, 0x49, 0x49, 0x49, 0x26],
  7: [0x40, 0x47, 0x48, 0x50, 0x60],
  8: [0x36, 0x49, 0x49, 0x49, 0x36],
  9: [0x32, 0x49, 0x49, 0x49, 0x3e],
  '!': [0x00, 0x00, 0x5f, 0x00, 0x00],
  '?': [0x20, 0x40, 0x4d, 0x50, 0x20],
  '-': [0x08, 0x08, 0x08, 0x08, 0x08],
  _: [0x40, 0x40, 0x40, 0x40, 0x40],
  '.': [0x00, 0x60, 0x60, 0x00, 0x00],
  ',': [0x00, 0x80, 0x60, 0x00, 0x00],
  ':': [0x00, 0x36, 0x36, 0x00, 0x00],
  ';': [0x00, 0x80, 0x36, 0x00, 0x00],
  '+': [0x08, 0x08, 0x3e, 0x08, 0x08],
  '=': [0x14, 0x14, 0x14, 0x14, 0x14],
  '<': [0x08, 0x14, 0x22, 0x41, 0x00],
  '>': [0x00, 0x41, 0x22, 0x14, 0x08],
  '/': [0x60, 0x10, 0x08, 0x04, 0x03],
  '\\': [0x03, 0x04, 0x08, 0x10, 0x60],
  '(': [0x00, 0x1c, 0x22, 0x41, 0x00],
  ')': [0x00, 0x41, 0x22, 0x1c, 0x00],
  '[': [0x00, 0x7f, 0x41, 0x41, 0x00],
  ']': [0x00, 0x41, 0x41, 0x7f, 0x00],
  '{': [0x00, 0x08, 0x36, 0x41, 0x00],
  '}': [0x00, 0x41, 0x36, 0x08, 0x00],
  '*': [0x14, 0x08, 0x3e, 0x08, 0x14],
  '#': [0x24, 0x7e, 0x24, 0x7e, 0x24],
  '@': [0x3e, 0x41, 0x5d, 0x55, 0x5e],
  '&': [0x36, 0x49, 0x55, 0x22, 0x50],
  '%': [0x62, 0x64, 0x08, 0x13, 0x23],
  $: [0x24, 0x2a, 0x7f, 0x2a, 0x12],
  '^': [0x04, 0x02, 0x01, 0x02, 0x04],
  '~': [0x02, 0x01, 0x02, 0x04, 0x02],
  '`': [0x00, 0x01, 0x02, 0x00, 0x00],
  "'": [0x00, 0x00, 0x07, 0x00, 0x00],
  '"': [0x00, 0x07, 0x00, 0x07, 0x00],
  '|': [0x00, 0x00, 0x7f, 0x00, 0x00],
};

// Custom font designed specifically for 8x8x8 cube 3D spinning
// Each letter is 5 columns wide, 7 pixels tall, perfectly centered for rotation
// Optimized for readability when spinning in 3D space
const CUBE8x8_FONT = {
  ' ': [0x00, 0x00, 0x00, 0x00, 0x00],

  // Vowels - extra clear for readability
  A: [0x3e, 0x09, 0x09, 0x09, 0x3e], // Simplified A
  E: [0x7f, 0x49, 0x49, 0x49, 0x41], // Clear E
  I: [0x00, 0x41, 0x7f, 0x41, 0x00], // Centered I
  O: [0x3e, 0x41, 0x41, 0x41, 0x3e], // Perfect O
  U: [0x3f, 0x40, 0x40, 0x40, 0x3f], // Clean U

  // Consonants - optimized for 3D visibility
  B: [0x7f, 0x49, 0x49, 0x49, 0x36], // Bold B
  C: [0x3e, 0x41, 0x41, 0x41, 0x22], // Open C
  D: [0x7f, 0x41, 0x41, 0x22, 0x1c], // Rounded D
  F: [0x7f, 0x09, 0x09, 0x09, 0x01], // Strong F
  G: [0x3e, 0x41, 0x49, 0x49, 0x3a], // Clear G
  H: [0x7f, 0x08, 0x08, 0x08, 0x7f], // Balanced H
  J: [0x20, 0x40, 0x41, 0x3f, 0x01], // Hooked J
  K: [0x7f, 0x08, 0x14, 0x22, 0x41], // Angular K
  L: [0x7f, 0x40, 0x40, 0x40, 0x40], // Simple L
  M: [0x7f, 0x02, 0x0c, 0x02, 0x7f], // Wide M
  N: [0x7f, 0x04, 0x08, 0x10, 0x7f], // Diagonal N
  P: [0x7f, 0x09, 0x09, 0x09, 0x06], // Compact P
  Q: [0x3e, 0x41, 0x51, 0x21, 0x5e], // Tailed Q
  R: [0x7f, 0x09, 0x19, 0x29, 0x46], // Legged R
  S: [0x26, 0x49, 0x49, 0x49, 0x32], // Curved S
  T: [0x01, 0x01, 0x7f, 0x01, 0x01], // Centered T
  V: [0x1f, 0x20, 0x40, 0x20, 0x1f], // Pointed V
  W: [0x3f, 0x40, 0x20, 0x40, 0x3f], // Double V
  X: [0x63, 0x14, 0x08, 0x14, 0x63], // Cross X
  Y: [0x03, 0x04, 0x78, 0x04, 0x03], // Forked Y
  Z: [0x61, 0x51, 0x49, 0x45, 0x43], // Zigzag Z

  // Numbers - clear and distinct
  0: [0x3e, 0x51, 0x49, 0x45, 0x3e], // Slashed 0
  1: [0x00, 0x42, 0x7f, 0x40, 0x00], // Simple 1
  2: [0x42, 0x61, 0x51, 0x49, 0x46], // Clear 2
  3: [0x21, 0x41, 0x49, 0x4d, 0x33], // Curved 3
  4: [0x18, 0x14, 0x12, 0x7f, 0x10], // Angled 4
  5: [0x27, 0x45, 0x45, 0x45, 0x39], // Squared 5
  6: [0x3c, 0x4a, 0x49, 0x49, 0x30], // Rounded 6
  7: [0x01, 0x71, 0x09, 0x05, 0x03], // Slanted 7
  8: [0x36, 0x49, 0x49, 0x49, 0x36], // Double 8
  9: [0x06, 0x49, 0x49, 0x29, 0x1e], // Flipped 6

  // Special characters
  '!': [0x00, 0x00, 0x5f, 0x00, 0x00],
  '?': [0x02, 0x01, 0x51, 0x09, 0x06],
  '.': [0x00, 0x60, 0x60, 0x00, 0x00],
  '-': [0x08, 0x08, 0x08, 0x08, 0x08],
  '+': [0x08, 0x08, 0x3e, 0x08, 0x08],
  '*': [0x14, 0x08, 0x3e, 0x08, 0x14],
  '/': [0x60, 0x10, 0x08, 0x04, 0x03],
  '\\': [0x03, 0x04, 0x08, 0x10, 0x60],
  '(': [0x00, 0x1c, 0x22, 0x41, 0x00],
  ')': [0x00, 0x41, 0x22, 0x1c, 0x00],
  '[': [0x00, 0x7f, 0x41, 0x41, 0x00],
  ']': [0x00, 0x41, 0x41, 0x7f, 0x00],
  ':': [0x00, 0x36, 0x36, 0x00, 0x00],
  ';': [0x00, 0x56, 0x36, 0x00, 0x00],
  '<': [0x08, 0x14, 0x22, 0x41, 0x00],
  '>': [0x00, 0x41, 0x22, 0x14, 0x08],
  '=': [0x14, 0x14, 0x14, 0x14, 0x14],
  '#': [0x14, 0x7f, 0x14, 0x7f, 0x14],
  '@': [0x3e, 0x41, 0x5d, 0x55, 0x5e],
  '&': [0x36, 0x49, 0x55, 0x22, 0x50],
  '%': [0x23, 0x13, 0x08, 0x64, 0x62],
  $: [0x24, 0x2a, 0x7f, 0x2a, 0x12],
  '^': [0x04, 0x02, 0x01, 0x02, 0x04],
  '~': [0x02, 0x01, 0x02, 0x04, 0x02],
  '`': [0x00, 0x01, 0x02, 0x04, 0x00],
  "'": [0x00, 0x00, 0x07, 0x00, 0x00],
  '"': [0x00, 0x07, 0x00, 0x07, 0x00],
  '|': [0x00, 0x00, 0x7f, 0x00, 0x00],
  _: [0x40, 0x40, 0x40, 0x40, 0x40],
  ',': [0x00, 0x80, 0x60, 0x00, 0x00],

  // Simple, tweak column values to refine appearance when previewing in 3D
  SMILE: [0x3c, 0x42, 0xa9, 0x85, 0x85, 0xa9, 0x42, 0x3c],
  SAD: [0x3c, 0x42, 0xa5, 0x89, 0x89, 0xa5, 0x42, 0x3c],
  WINK: [0x3c, 0x42, 0x89, 0x85, 0x85, 0xa9, 0x42, 0x3c],
  HEART: [0x3c, 0x46, 0x23, 0x23, 0x46, 0x3c],
  SHOCK: [0x3c, 0x42, 0xa1, 0x8d, 0x8d, 0xa1, 0x42, 0x3c],
  ANGRY: [0x3c, 0x42, 0xe5, 0x85, 0x85, 0xe5, 0x42, 0x3c],
  BORED: [0x3c, 0x42, 0xa5, 0x85, 0x85, 0xa5, 0x42, 0x3c],
  TONGUE: [0x3c, 0x42, 0xaf, 0x89, 0x89, 0xaf, 0x42, 0x3c],

  // Arrows
  ARROW_UP: [0x00, 0x20, 0x60, 0xff, 0xff, 0x60, 0x20, 0x00],
  ARROW_DOWN: [0x00, 0x04, 0x06, 0xff, 0xff, 0x06, 0x04, 0x00],
  ARROW_LEFT: [0x18, 0x3c, 0x7e, 0x18, 0x18, 0x18, 0x18, 0x18],
  ARROW_RIGHT: [0x18, 0x18, 0x18, 0x18, 0x18, 0x7e, 0x3c, 0x18],

  // Card suits (heart already covered above)
  SPADE: [0x10, 0x38, 0x7a, 0xff, 0xff, 0x7a, 0x38, 0x10],
  DIAMOND: [0x18, 0x3c, 0x7e, 0xff, 0xff, 0x7e, 0x3c, 0x18],
  CLUB: [0x30, 0x78, 0xf9, 0xff, 0xff, 0xf9, 0x78, 0x30],

  // Seasonal
  SNOWFLAKE: [0x91, 0x52, 0x34, 0xff, 0x18, 0x34, 0x52, 0x91],
  TREE: [0x04, 0x2c, 0x7c, 0xff, 0xff, 0x7c, 0x2c, 0x04],
  PUMPKIN: [0x1c, 0x3e, 0x3f, 0xff, 0xff, 0x3f, 0x3e, 0x1c],

  // Retro
  GHOST: [0x3f, 0x7e, 0xff, 0xfe, 0xff, 0xfe, 0x7f, 0x7e],
  PACMAN: [0x3c, 0x7e, 0xff, 0xff, 0xe7, 0xe7, 0x66, 0x00],
  INVADER: [0x1e, 0x38, 0x6f, 0xfd, 0xfc, 0x6f, 0x39, 0x1e],
};

// Stylized Cursive/Script Font for continuous flowing text
// Lowercase letters feature trailing connection pixels to link words together
const CURSIVE_FONT = {
  ' ': [0x00, 0x00, 0x00, 0x00, 0x00],

  // Script Uppercase
  A: [0x78, 0x16, 0x11, 0x16, 0x78],
  B: [0x7f, 0x49, 0x49, 0x49, 0x36],
  C: [0x3e, 0x41, 0x41, 0x41, 0x22],
  D: [0x7f, 0x41, 0x41, 0x22, 0x1c],
  E: [0x7f, 0x49, 0x49, 0x49, 0x41],
  F: [0x7f, 0x09, 0x09, 0x09, 0x01],
  G: [0x3e, 0x41, 0x49, 0x49, 0x7a],
  H: [0x7f, 0x08, 0x08, 0x08, 0x7f],
  I: [0x00, 0x41, 0x7f, 0x41, 0x00],
  J: [0x20, 0x40, 0x41, 0x3f, 0x01],
  K: [0x7f, 0x08, 0x14, 0x22, 0x41],
  L: [0x7f, 0x40, 0x40, 0x40, 0x40],
  M: [0x7f, 0x02, 0x04, 0x02, 0x7f],
  N: [0x7f, 0x04, 0x08, 0x10, 0x7f],
  O: [0x3e, 0x41, 0x41, 0x41, 0x3e],
  P: [0x7f, 0x09, 0x09, 0x09, 0x06],
  Q: [0x3e, 0x41, 0x51, 0x21, 0x5e],
  R: [0x7f, 0x09, 0x19, 0x29, 0x46],
  S: [0x46, 0x49, 0x49, 0x49, 0x31],
  T: [0x01, 0x01, 0x7f, 0x01, 0x01],
  U: [0x3f, 0x40, 0x40, 0x40, 0x3f],
  V: [0x1f, 0x20, 0x40, 0x20, 0x1f],
  W: [0x7f, 0x20, 0x18, 0x20, 0x7f],
  X: [0x63, 0x14, 0x08, 0x14, 0x63],
  Y: [0x03, 0x04, 0x78, 0x04, 0x03],
  Z: [0x61, 0x51, 0x49, 0x45, 0x43],

  // Linked Script Lowercase
  a: [0x20, 0x54, 0x54, 0x78, 0x40],
  b: [0x7f, 0x48, 0x48, 0x30, 0x40],
  c: [0x38, 0x44, 0x44, 0x48, 0x40],
  d: [0x38, 0x44, 0x44, 0x7f, 0x40],
  e: [0x38, 0x54, 0x54, 0x58, 0x40],
  f: [0x08, 0x7e, 0x09, 0x01, 0x00],
  g: [0x18, 0xa4, 0xa4, 0x7c, 0x80],
  h: [0x7f, 0x08, 0x04, 0x78, 0x40],
  i: [0x00, 0x44, 0x7d, 0x40, 0x40],
  j: [0x20, 0x40, 0x44, 0x3d, 0x80],
  k: [0x7f, 0x10, 0x28, 0x44, 0x40],
  l: [0x00, 0x41, 0x7f, 0x40, 0x40],
  m: [0x7c, 0x04, 0x78, 0x04, 0x78],
  n: [0x7c, 0x08, 0x04, 0x78, 0x40],
  o: [0x38, 0x44, 0x44, 0x38, 0x40],
  p: [0xfc, 0x24, 0x24, 0x18, 0x00],
  q: [0x18, 0x24, 0x24, 0xfc, 0x80],
  r: [0x7c, 0x08, 0x04, 0x0c, 0x40],
  s: [0x48, 0x54, 0x54, 0x28, 0x40],
  t: [0x04, 0x3f, 0x44, 0x40, 0x40],
  u: [0x3c, 0x40, 0x40, 0x7c, 0x40],
  v: [0x1c, 0x20, 0x40, 0x20, 0x40],
  w: [0x3c, 0x40, 0x3c, 0x40, 0x3c],
  x: [0x44, 0x28, 0x10, 0x28, 0x44],
  y: [0x1c, 0xa0, 0xa0, 0x7c, 0x80],
  z: [0x44, 0x64, 0x54, 0x4c, 0x40],

  // Shared Punctuation
  '!': [0x00, 0x00, 0x5f, 0x00, 0x00],
  '?': [0x20, 0x40, 0x4d, 0x50, 0x20],
  '.': [0x00, 0x60, 0x60, 0x00, 0x00],
  ',': [0x00, 0x80, 0x60, 0x00, 0x00],
};
// Helper: flip font column bits vertically (fix upside-down letters)
function flipColumnVertical(col) {
  let flipped = 0;
  for (let z = 0; z < 7; z++) {
    if ((col >> z) & 1) {
      flipped |= 1 << (6 - z);
    }
  }
  return flipped;
}

// Helper: set a column at a specific position on the cube
// Updated to match physical cube orientation - flip vertically for proper letter orientation
// position goes from 0-31 for a 4-sided wrap (8 positions per side)
// position 0-7: front face (y=7, x=0-7)
// position 8-15: right face (x=7, y=7-0)
// position 16-23: back face (y=0, x=7-0)
// position 24-31: left face (x=0, y=0-7)
function setColumnAtPosition(frame, col, position) {
  // Flip the column vertically so letters appear right-side up
  const finalCol = flipColumnVertical(col);

  let mask = 0;
  for (let z = 0; z < 7; z++) {
    if ((finalCol >> z) & 1) mask |= 1 << z;
  }

  if (position >= 0 && position < 8) {
    // Front face: y=7, x=position
    frame[8 * 7 + position] = mask;
  } else if (position >= 8 && position < 16) {
    // Right face: x=7, y=7-(position-8)
    const y = 7 - (position - 8);
    frame[8 * y + 7] = mask;
  } else if (position >= 16 && position < 24) {
    // Back face: y=0, x=7-(position-16)
    const x = 7 - (position - 16);
    frame[8 * 0 + x] = mask;
  } else if (position >= 24 && position < 32) {
    // Left face: x=0, y=position-24
    const y = position - 24;
    frame[8 * y + 0] = mask;
  }
}

// Scroll text continuously around specified number of sides. Returns array of frames.
// sides: number of sides (1-4) to use for scrolling
// direction: 'ltr' (default) or 'rtl' (render columns for right-to-left preview)
export function generateTextFrames(
  text = '',
  sides = 1,
  direction = 'ltr',
  font = 'standard',
) {
  const fontMap = font === 'cursive' ? CURSIVE_FONT : FONT5x7;
  const t = String(text || '');
  if (!t) return [];

  // Build column buffer - forward order to match physical cube direction
  const cols = [];

  // Build in forward order (this will make it scroll in the correct direction)
  for (let i = 0; i < t.length; i++) {
    const ch = t[i];
    // Try the exact character first (so lowercase glyphs are reachable),
    // then its uppercase form (covers fonts with a smaller symbol set,
    // like CURSIVE_FONT's punctuation), then fall back to a blank column.
    const glyph = fontMap[ch] || fontMap[ch.toUpperCase()] || fontMap[' '];
    cols.push(0x00); // spacing
    // Add columns in forward order
    for (let ci = 0; ci < glyph.length; ci++) {
      cols.push(glyph[ci]);
    }
  }

  const padding = [];
  const buffer = padding.concat(cols).concat(padding);

  // Total positions available based on number of sides
  const positionsPerSide = 8;
  const totalPositions = sides * positionsPerSide;

  const frames = [];

  // Create frames where text flows continuously around the sides
  // We need enough frames to scroll the entire buffer through the visible window
  const numFrames = buffer.length + totalPositions;

  for (let frameIdx = 0; frameIdx < numFrames; frameIdx++) {
    const frame = new Array(64).fill(0x00);

    // For this frame, render columns at each visible position
    for (let pos = 0; pos < totalPositions; pos++) {
      // Reverse the buffer index calculation to change scroll direction
      const bufferIndex = frameIdx + pos - totalPositions;

      if (bufferIndex >= 0 && bufferIndex < buffer.length) {
        const col = buffer[bufferIndex];
        setColumnAtPosition(frame, col, pos);
      }
    }

    frames.push(frame);
  }

  return frames;
}

// Render glyph columns to a specific face with optional thickness
function renderColumnsToFace(glyph, face = 'front', thickness = 1) {
  const frame = new Array(64).fill(0x00);

  for (let cx = 0; cx < Math.min(5, glyph.length); cx++) {
    const col = flipColumnVertical(glyph[cx] || 0);

    // Center the glyph horizontally
    const x = cx + 1; // This centers a 5-wide glyph in 8-wide space

    let mask = 0;
    for (let z = 0; z < 7; z++) {
      if ((col >> z) & 1) {
        mask |= 1 << z;
      }
    }

    if (face === 'front') {
      // Place on front face (y = 7) and optionally one layer back for thickness
      frame[8 * 7 + x] = mask;
      if (thickness > 1) {
        frame[8 * 6 + x] = mask; // One layer back
      }
    }
    // Add other faces if needed
  }

  return frame;
}

// Render a single glyph and produce animated frames

export function generateGlyphFrames(
  char = 'A',
  steps = 4,
  mode = 'flat',
  font = 'standard',
) {
  const raw = String(char || ' ');

  if (mode === '3d') {
    // CUBE8x8_FONT (icons + letters) has no distinct lowercase set, so 3D
    // spin always renders the uppercase/icon form.
    return generate3DGlyphSpin(raw.toUpperCase(), steps);
  } else {
    // Flat rotation on front face -- try the exact character first (so
    // lowercase letters are reachable), then its uppercase form, then a
    // blank column.
    const fontMap = font === 'cursive' ? CURSIVE_FONT : FONT5x7;
    const glyph = fontMap[raw] || fontMap[raw.toUpperCase()] || fontMap[' '];
    const base = renderColumnsToFace(glyph, 'front', 2);
    const res = [base];
    let cur = base;
    for (let s = 1; s < steps; s++) {
      cur = rotateZ90(cur);
      res.push(cur.slice());
    }
    return res;
  }
}

function generate3DGlyphSpin(glyph, steps) {
  const frames = [];

  // Use the new CUBE8x8_FONT for optimal 3D display
  const charPattern = CUBE8x8_FONT[glyph.toUpperCase()] || CUBE8x8_FONT[' '];

  const CUBE_SIZE = 8;
  const ACTUAL_WIDTH = charPattern.length;

  // 1. DYNAMIC HEIGHT CALCULATOR
  // Scans the array values to check if any column uses all 8 vertical bits
  let maxBitRow = 0;
  for (let col = 0; col < ACTUAL_WIDTH; col++) {
    const val = charPattern[col];
    for (let bit = 7; bit >= 0; bit--) {
      if (val & (1 << bit) && bit > maxBitRow) {
        maxBitRow = bit;
      }
    }
  }
  // The row height matches the highest active bit + 1 (e.g., bit 7 active = height 8)
  const ACTUAL_HEIGHT = Math.max(7, maxBitRow + 1);

  // Symmetrical centers across the 2D plane
  const centerX = 3.5;
  const centerY = 3.5;

  // 2. DYNAMIC VERTICAL ALIGNMENT
  // Safely pins the bottom layer to index 0 if the icon fills all 8 layers
  const charStartY = ACTUAL_HEIGHT >= 8 ? 0 : Math.round(4 - ACTUAL_HEIGHT / 2);

  // Dynamic horizontal midpoint balancing
  const localCenter = (ACTUAL_WIDTH - 1) / 2;

  // Icons drawn full-height (0-7 rows) get a different vertical orientation
  // in the 3D spin than the narrower letter glyphs -- this list is anything
  // in CUBE8x8_FONT that isn't a letter/number/punctuation character.
  const fullIconKeys = [
    'SMILE',
    'SAD',
    'WINK',
    'HEART',
    'SHOCK',
    'ANGRY',
    'BORED',
    'TONGUE',
    'ARROW_UP',
    'ARROW_DOWN',
    'ARROW_LEFT',
    'ARROW_RIGHT',
    'SPADE',
    'DIAMOND',
    'CLUB',
    'SNOWFLAKE',
    'TREE',
    'PUMPKIN',
    'GHOST',
    'PACMAN',
    'INVADER',
  ];
  const isEmoticon = fullIconKeys.includes(String(glyph).toUpperCase());

  for (let step = 0; step < steps; step++) {
    const frame = new Array(64).fill(0x00);
    const angle = (step / steps) * Math.PI * 2;

    for (let col = 0; col < ACTUAL_WIDTH; col++) {
      const columnData = charPattern[col];

      // 3. FIX: Check all layers up to the dynamic character height limit
      for (let row = 0; row < ACTUAL_HEIGHT; row++) {
        if (columnData & (1 << row)) {
          const charX = col - localCenter;
          const charZ = isEmoticon ? row : ACTUAL_HEIGHT - 1 - row;

          // Thickness logic loop
          for (let thickness = 0; thickness < 2; thickness++) {
            const charY = thickness - 0.5;

            // Rotation equations
            const cosAngle = Math.cos(angle);
            const sinAngle = Math.sin(angle);

            const rotatedX = charX * cosAngle - charY * sinAngle;
            const rotatedY = charX * sinAngle + charY * cosAngle;

            // Final coordinate maps
            const cubeX = Math.round(centerX + rotatedX);
            const finalY = Math.round(centerY + rotatedY);
            const cubeZ = charStartY + charZ;

            // Bounds checking
            if (
              cubeX >= 0 &&
              cubeX < CUBE_SIZE &&
              finalY >= 0 &&
              finalY < CUBE_SIZE &&
              cubeZ >= 0 &&
              cubeZ < CUBE_SIZE
            ) {
              const byteIndex = CUBE_SIZE * finalY + cubeX;
              if (byteIndex >= 0 && byteIndex < 64) {
                frame[byteIndex] |= 1 << cubeZ;
              }
            }
          }
        }
      }
    }

    frames.push(frame);
  }

  return frames;
}
// Places an 8-column bitmap directly on the front face (2 layers thick),
// no font-centering offset -- used for imported images, which already
// fill the full 8x8 width, unlike the narrower 5-wide font glyphs.
// `columns[x]` is a byte whose bit z is lit if that pixel should be on;
// bit 0 = bottom row, bit 7 = top row (matches the convention used by the
// icon font and every procedural pattern in patterns.js).
export function renderImageToFace(columns, thickness = 2) {
  const frame = new Array(64).fill(0x00);
  for (let x = 0; x < Math.min(8, columns.length); x++) {
    const mask = columns[x] & 0xff;
    frame[8 * 7 + x] = mask;
    if (thickness > 1) frame[8 * 6 + x] = mask;
  }
  return frame;
}

// Builds an animation from an imported image's column data: a single
// static frame, or (if spin is true) a short flat rotation around the
// vertical axis, same idea as Spin Glyph's "flat" mode.
export function generateImageFrames(columns, steps = 6, spin = true) {
  const base = renderImageToFace(columns, 2);
  if (!spin || steps <= 1) return [base];
  const res = [base];
  let cur = base;
  for (let s = 1; s < steps; s++) {
    cur = rotateZ90(cur);
    res.push(cur.slice());
  }
  return res;
}
