// Utilities to produce sample frames and convert frames to Arduino C arrays
import { mirrorX, mirrorY } from './drawHelpers.js';

export function framesToCArray(frames, name) {
  if (!frames || frames.length === 0) return '// no frames';

  // Apply mirroring transformations to match physical cube orientation
  const transformedFrames = frames.map((frame) => mirrorX(frame));

  const frameCount = transformedFrames.length;
  const cols = 64;
  let out = `// Generated by LED Cube Designer\n#define ${name}_FRAME_COUNT ${frameCount}\n\nconst byte ${name}[${frameCount}][${cols}] = {\n`;

  transformedFrames.forEach((f, fi) => {
    out += `  // Frame ${fi}\n  {`;
    for (let i = 0; i < cols; i++) {
      const v = f[i] || 0;
      out += '0x' + v.toString(16).toUpperCase().padStart(2, '0');
      if (i < cols - 1) out += ', ';
      if ((i + 1) % 8 === 0 && i < cols - 1) out += '\n   ';
    }
    out += '}';
    if (fi < frameCount - 1) out += ',\n\n';
    else out += '\n';
  });

  out += '};\n';
  return out;
}

export function generateHFile(name, frames) {
  const arr = framesToCArray(frames, name);
  const guard = `_${name}_H_`.toUpperCase();
  let out =
    `#ifndef ${guard}\n#define ${guard}\n\n#include <Arduino.h>\n\n` +
    arr +
    `\n#endif // ${guard}\n`;
  return out;
}

export function generateSketch(name, frames) {
  // generate the C array text first
  let arr = framesToCArray(frames, name);

  // replace the array declaration to place it in flash (PROGMEM)
  const header = `const byte ${name}[${frames.length}][64] = {`;
  const headerProg = `const byte ${name}[${frames.length}][64] PROGMEM = {`;
  arr = arr.replace(header, headerProg);

  // sketch template using PROGMEM and pgm_read_byte
  const sketch = `// Generated Arduino sketch for ${name}\n\n#include <Arduino.h>\n#include <avr/pgmspace.h>\n\n${arr}\n\n// send one frame stored in PROGMEM (framePtr points to 64 bytes)\nvoid sendFrameFromPROGMEM(const uint8_t *framePtr) {\n  Serial.write(0xF2);\n  for (int i = 0; i < 64; i++) {\n    uint8_t b = pgm_read_byte(framePtr + i);\n    Serial.write(b);\n  }\n}\n\nvoid setup(){\n  Serial.begin(38400);\n  delay(500);\n  // send open command\n  for(int i=0;i<70;i++) Serial.write(0xAD);\n  delay(200);\n}\n\nvoid loop(){\n  for (int f = 0; f < ${name}_FRAME_COUNT; f++) {\n    const uint8_t *framePtr = ${name}[f];\n    sendFrameFromPROGMEM(framePtr);\n    delay(200);\n  }\n  // keep looping\n}\n`;

  return sketch;
}

// Generate a receiver sketch that accepts frames over Serial with checksum/ACK
export function generateStreamingReceiverSketch() {
  const sketch = `// Streaming receiver sketch for LED Cube - receives frames over Serial
//
// IMPORTANT: This sketch must be the one currently flashed on your board
// for the "Send" button on the website to work. If your board is instead
// running your normal animation sketch (e.g. an exported ANIM.ino), it is
// not listening for serial data at all, and "Send" will appear to do
// nothing.
//
// IMPORTANT: displayFrame() below is a placeholder. This tool has no way
// to know how your specific cube is wired (shift registers, multiplexing,
// a driver library, etc.), so you must fill it in with whatever code
// already lights up your cube from a 64-byte frame buffer -- the same
// logic your working animation sketch uses, just called once per received
// frame instead of from a baked-in array.

#include <Arduino.h>

const uint8_t FRAME_MARKER = 0xF2;
const uint8_t ACK = 0xAA;
const uint8_t NACK = 0xFF;

// Replace this with your cube display function. "frame" is 64 bytes;
// frame[8*y + x] is a column, bit z of that byte is that column's z-th LED.
void displayFrame(const uint8_t *frame) {
  // TODO: map the 64-byte frame into your cube wiring and update outputs.
  // Example placeholder: blink onboard LED to indicate a frame was received.
  digitalWrite(LED_BUILTIN, HIGH);
  delay(20);
  digitalWrite(LED_BUILTIN, LOW);
}

void setup() {
  Serial.begin(38400);
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  if (Serial.available() <= 0) return;
  int c = Serial.read();
  if (c != FRAME_MARKER) return; // also silently skips the open/close (0xAD/0xED) marker bytes

  // read 64 bytes for frame
  uint8_t buf[64];
  unsigned long start = millis();
  int got = 0;
  while (got < 64 && (millis() - start) < 1000) {
    if (Serial.available() > 0) {
      int v = Serial.read();
      if (v >= 0) buf[got++] = (uint8_t)v;
    }
  }
  if (got < 64) {
    Serial.write(NACK);
    return;
  }

  // read checksum (sum of the 64 data bytes, mod 256 -- matches what the
  // website's Send button computes and appends after each frame)
  start = millis();
  while (Serial.available() == 0 && (millis() - start) < 500) ;
  if (Serial.available() == 0) {
    Serial.write(NACK);
    return;
  }
  uint8_t checksum = (uint8_t)Serial.read();

  uint8_t sum = 0;
  for (int i = 0; i < 64; i++) sum += buf[i];
  if (sum != checksum) {
    Serial.write(NACK);
    return;
  }

  // valid frame - display it, THEN acknowledge. Acking first would let the
  // sender fire the next 66-byte frame while this board is still busy
  // inside displayFrame(); on boards with only a 64-byte serial RX buffer,
  // any real (non-trivial) displayFrame() implementation can then overflow
  // that buffer and silently drop bytes, corrupting the *next* frame's
  // checksum. Displaying first gives the sender correct backpressure.
  displayFrame(buf);
  Serial.write(ACK);
}`;

  return sketch;
}

// ========== TEXT & GLYPH ANIMATION ==========

// Simple 5x7 font (columns, LSB = top row)
const FONT5x7 = {
  ' ': [0x00, 0x00, 0x00, 0x00, 0x00],
  A: [0x7c, 0x12, 0x11, 0x12, 0x7c],
  B: [0x7f, 0x49, 0x49, 0x49, 0x36],
  C: [0x3e, 0x41, 0x41, 0x41, 0x22],
  D: [0x7f, 0x41, 0x41, 0x22, 0x1c],
  E: [0x7f, 0x49, 0x49, 0x49, 0x41],
  F: [0x7f, 0x09, 0x09, 0x09, 0x01],
  G: [0x3e, 0x41, 0x49, 0x49, 0x7a],
  H: [0x7f, 0x08, 0x08, 0x08, 0x7f],
  I: [0x00, 0x41, 0x7f, 0x41, 0x00],
  J: [0x20, 0x40, 0x41, 0x3f, 0x01],
  K: [0x7f, 0x08, 0x14, 0x22, 0x41],
  L: [0x7f, 0x40, 0x40, 0x40, 0x40],
  M: [0x7f, 0x02, 0x04, 0x02, 0x7f],
  N: [0x7f, 0x04, 0x08, 0x10, 0x7f],
  O: [0x3e, 0x41, 0x41, 0x41, 0x3e],
  P: [0x7f, 0x09, 0x09, 0x09, 0x06],
  Q: [0x3e, 0x41, 0x51, 0x21, 0x5e],
  R: [0x7f, 0x09, 0x19, 0x29, 0x46],
  S: [0x46, 0x49, 0x49, 0x49, 0x31],
  T: [0x01, 0x01, 0x7f, 0x01, 0x01],
  U: [0x3f, 0x40, 0x40, 0x40, 0x3f],
  V: [0x1f, 0x20, 0x40, 0x20, 0x1f],
  W: [0x7f, 0x20, 0x18, 0x20, 0x7f],
  X: [0x63, 0x14, 0x08, 0x14, 0x63],
  Y: [0x03, 0x04, 0x78, 0x04, 0x03],
  Z: [0x61, 0x51, 0x49, 0x45, 0x43],
  0: [0x3e, 0x45, 0x49, 0x51, 0x3e],
  1: [0x00, 0x21, 0x7f, 0x01, 0x00],
  2: [0x23, 0x45, 0x49, 0x49, 0x31],
  3: [0x22, 0x41, 0x49, 0x49, 0x36],
  4: [0x0c, 0x14, 0x24, 0x7f, 0x04],
  5: [0x72, 0x51, 0x51, 0x51, 0x4e],
  6: [0x3e, 0x49, 0x49, 0x49, 0x26],
  7: [0x40, 0x47, 0x48, 0x50, 0x60],
  8: [0x36, 0x49, 0x49, 0x49, 0x36],
  9: [0x32, 0x49, 0x49, 0x49, 0x3e],
  '!': [0x00, 0x00, 0x5f, 0x00, 0x00],
  '?': [0x20, 0x40, 0x4d, 0x50, 0x20],
  '-': [0x08, 0x08, 0x08, 0x08, 0x08],
  _: [0x40, 0x40, 0x40, 0x40, 0x40],
  '.': [0x00, 0x60, 0x60, 0x00, 0x00],
  ',': [0x00, 0x80, 0x60, 0x00, 0x00],
  ':': [0x00, 0x36, 0x36, 0x00, 0x00],
  ';': [0x00, 0x80, 0x36, 0x00, 0x00],
  '+': [0x08, 0x08, 0x3e, 0x08, 0x08],
  '=': [0x14, 0x14, 0x14, 0x14, 0x14],
  '<': [0x08, 0x14, 0x22, 0x41, 0x00],
  '>': [0x00, 0x41, 0x22, 0x14, 0x08],
  '/': [0x60, 0x10, 0x08, 0x04, 0x03],
  '\\': [0x03, 0x04, 0x08, 0x10, 0x60],
  '(': [0x00, 0x1c, 0x22, 0x41, 0x00],
  ')': [0x00, 0x41, 0x22, 0x1c, 0x00],
  '[': [0x00, 0x7f, 0x41, 0x41, 0x00],
  ']': [0x00, 0x41, 0x41, 0x7f, 0x00],
  '{': [0x00, 0x08, 0x36, 0x41, 0x00],
  '}': [0x00, 0x41, 0x36, 0x08, 0x00],
  '*': [0x14, 0x08, 0x3e, 0x08, 0x14],
  '#': [0x24, 0x7e, 0x24, 0x7e, 0x24],
  '@': [0x3e, 0x41, 0x5d, 0x55, 0x5e],
  '&': [0x36, 0x49, 0x55, 0x22, 0x50],
  '%': [0x62, 0x64, 0x08, 0x13, 0x23],
  $: [0x24, 0x2a, 0x7f, 0x2a, 0x12],
  '^': [0x04, 0x02, 0x01, 0x02, 0x04],
  '~': [0x02, 0x01, 0x02, 0x04, 0x02],
  '`': [0x00, 0x01, 0x02, 0x00, 0x00],
  "'": [0x00, 0x00, 0x07, 0x00, 0x00],
  '"': [0x00, 0x07, 0x00, 0x07, 0x00],
  '|': [0x00, 0x00, 0x7f, 0x00, 0x00],
};

// Custom font designed specifically for 8x8x8 cube 3D spinning
// Each letter is 5 columns wide, 7 pixels tall, perfectly centered for rotation
// Optimized for readability when spinning in 3D space
const CUBE8x8_FONT = {
  ' ': [0x00, 0x00, 0x00, 0x00, 0x00],

  // Vowels - extra clear for readability
  A: [0x3e, 0x09, 0x09, 0x09, 0x3e], // Simplified A
  E: [0x7f, 0x49, 0x49, 0x49, 0x41], // Clear E
  I: [0x00, 0x41, 0x7f, 0x41, 0x00], // Centered I
  O: [0x3e, 0x41, 0x41, 0x41, 0x3e], // Perfect O
  U: [0x3f, 0x40, 0x40, 0x40, 0x3f], // Clean U

  // Consonants - optimized for 3D visibility
  B: [0x7f, 0x49, 0x49, 0x49, 0x36], // Bold B
  C: [0x3e, 0x41, 0x41, 0x41, 0x22], // Open C
  D: [0x7f, 0x41, 0x41, 0x22, 0x1c], // Rounded D
  F: [0x7f, 0x09, 0x09, 0x09, 0x01], // Strong F
  G: [0x3e, 0x41, 0x49, 0x49, 0x3a], // Clear G
  H: [0x7f, 0x08, 0x08, 0x08, 0x7f], // Balanced H
  J: [0x20, 0x40, 0x41, 0x3f, 0x01], // Hooked J
  K: [0x7f, 0x08, 0x14, 0x22, 0x41], // Angular K
  L: [0x7f, 0x40, 0x40, 0x40, 0x40], // Simple L
  M: [0x7f, 0x02, 0x0c, 0x02, 0x7f], // Wide M
  N: [0x7f, 0x04, 0x08, 0x10, 0x7f], // Diagonal N
  P: [0x7f, 0x09, 0x09, 0x09, 0x06], // Compact P
  Q: [0x3e, 0x41, 0x51, 0x21, 0x5e], // Tailed Q
  R: [0x7f, 0x09, 0x19, 0x29, 0x46], // Legged R
  S: [0x26, 0x49, 0x49, 0x49, 0x32], // Curved S
  T: [0x01, 0x01, 0x7f, 0x01, 0x01], // Centered T
  V: [0x1f, 0x20, 0x40, 0x20, 0x1f], // Pointed V
  W: [0x3f, 0x40, 0x20, 0x40, 0x3f], // Double V
  X: [0x63, 0x14, 0x08, 0x14, 0x63], // Cross X
  Y: [0x03, 0x04, 0x78, 0x04, 0x03], // Forked Y
  Z: [0x61, 0x51, 0x49, 0x45, 0x43], // Zigzag Z

  // Numbers - clear and distinct
  0: [0x3e, 0x51, 0x49, 0x45, 0x3e], // Slashed 0
  1: [0x00, 0x42, 0x7f, 0x40, 0x00], // Simple 1
  2: [0x42, 0x61, 0x51, 0x49, 0x46], // Clear 2
  3: [0x21, 0x41, 0x49, 0x4d, 0x33], // Curved 3
  4: [0x18, 0x14, 0x12, 0x7f, 0x10], // Angled 4
  5: [0x27, 0x45, 0x45, 0x45, 0x39], // Squared 5
  6: [0x3c, 0x4a, 0x49, 0x49, 0x30], // Rounded 6
  7: [0x01, 0x71, 0x09, 0x05, 0x03], // Slanted 7
  8: [0x36, 0x49, 0x49, 0x49, 0x36], // Double 8
  9: [0x06, 0x49, 0x49, 0x29, 0x1e], // Flipped 6

  // Special characters
  '!': [0x00, 0x00, 0x5f, 0x00, 0x00],
  '?': [0x02, 0x01, 0x51, 0x09, 0x06],
  '.': [0x00, 0x60, 0x60, 0x00, 0x00],
  '-': [0x08, 0x08, 0x08, 0x08, 0x08],
  '+': [0x08, 0x08, 0x3e, 0x08, 0x08],
  '*': [0x14, 0x08, 0x3e, 0x08, 0x14],
  '/': [0x60, 0x10, 0x08, 0x04, 0x03],
  '\\': [0x03, 0x04, 0x08, 0x10, 0x60],
  '(': [0x00, 0x1c, 0x22, 0x41, 0x00],
  ')': [0x00, 0x41, 0x22, 0x1c, 0x00],
  '[': [0x00, 0x7f, 0x41, 0x41, 0x00],
  ']': [0x00, 0x41, 0x41, 0x7f, 0x00],
  ':': [0x00, 0x36, 0x36, 0x00, 0x00],
  ';': [0x00, 0x56, 0x36, 0x00, 0x00],
  '<': [0x08, 0x14, 0x22, 0x41, 0x00],
  '>': [0x00, 0x41, 0x22, 0x14, 0x08],
  '=': [0x14, 0x14, 0x14, 0x14, 0x14],
  '#': [0x14, 0x7f, 0x14, 0x7f, 0x14],
  '@': [0x3e, 0x41, 0x5d, 0x55, 0x5e],
  '&': [0x36, 0x49, 0x55, 0x22, 0x50],
  '%': [0x23, 0x13, 0x08, 0x64, 0x62],
  $: [0x24, 0x2a, 0x7f, 0x2a, 0x12],
  '^': [0x04, 0x02, 0x01, 0x02, 0x04],
  '~': [0x02, 0x01, 0x02, 0x04, 0x02],
  '`': [0x00, 0x01, 0x02, 0x04, 0x00],
  "'": [0x00, 0x00, 0x07, 0x00, 0x00],
  '"': [0x00, 0x07, 0x00, 0x07, 0x00],
  '|': [0x00, 0x00, 0x7f, 0x00, 0x00],
  _: [0x40, 0x40, 0x40, 0x40, 0x40],
  ',': [0x00, 0x80, 0x60, 0x00, 0x00],

  // Simple, tweak column values to refine appearance when previewing in 3D
  SMILE: [0x3C, 0x42, 0xA9, 0x85, 0x85, 0xA9, 0x42, 0x3C],
  SAD: [0x3C, 0x42, 0xA5, 0x89, 0x89, 0xA5, 0x42, 0x3C],
  WINK: [0x3C, 0x42, 0x89, 0x85, 0x85, 0xA9, 0x42, 0x3C],
  HEART: [0x3c, 0x46, 0x23, 0x23, 0x46, 0x3c],
  SHOCK: [ 0x3C, 0x42, 0xA1, 0x8D, 0x8D, 0xA1, 0x42, 0x3C],
  ANGRY: [0x3C, 0x42, 0xE5, 0x85, 0x85, 0xE5, 0x42, 0x3C],
  BORED: [0x3C, 0x42, 0xA5, 0x85, 0x85, 0xA5, 0x42, 0x3C],
  TONGUE: [0x3C, 0x42, 0xAF, 0x89, 0x89, 0xAF, 0x42, 0x3C],

  // Arrows
  ARROW_UP: [0x00, 0x20, 0x60, 0xff, 0xff, 0x60, 0x20, 0x00],
  ARROW_DOWN: [0x00, 0x04, 0x06, 0xff, 0xff, 0x06, 0x04, 0x00],
  ARROW_LEFT: [0x18, 0x3c, 0x7e, 0x18, 0x18, 0x18, 0x18, 0x18],
  ARROW_RIGHT: [0x18, 0x18, 0x18, 0x18, 0x18, 0x7e, 0x3c, 0x18],

  // Card suits (heart already covered above)
  SPADE: [0x10, 0x38, 0x7a, 0xff, 0xff, 0x7a, 0x38, 0x10],
  DIAMOND: [0x18, 0x3c, 0x7e, 0xff, 0xff, 0x7e, 0x3c, 0x18],
  CLUB: [0x30, 0x78, 0xf9, 0xff, 0xff, 0xf9, 0x78, 0x30],

  // Seasonal
  SNOWFLAKE: [0x91, 0x52, 0x34, 0xff, 0x18, 0x34, 0x52, 0x91],
  TREE: [0x04, 0x2c, 0x7c, 0xff, 0xff, 0x7c, 0x2c, 0x04],
  PUMPKIN: [0x1c, 0x3e, 0x3f, 0xff, 0xff, 0x3f, 0x3e, 0x1c],

  // Retro
  GHOST: [0x3f, 0x7e, 0xff, 0xfe, 0xff, 0xfe, 0x7f, 0x7e],
  PACMAN: [0x3c, 0x7e, 0xff, 0xff, 0xe7, 0xe7, 0x66, 0x00],
  INVADER: [0x1e, 0x38, 0x6f, 0xfd, 0xfc, 0x6f, 0x39, 0x1e],
};

// Helper: flip font column bits vertically (fix upside-down letters)
function flipColumnVertical(col) {
  let flipped = 0;
  for (let z = 0; z < 7; z++) {
    if ((col >> z) & 1) {
      flipped |= 1 << (6 - z);
    }
  }
  return flipped;
}

// Helper: set a column at a specific position on the cube
// Updated to match physical cube orientation - flip vertically for proper letter orientation
// position goes from 0-31 for a 4-sided wrap (8 positions per side)
// position 0-7: front face (y=7, x=0-7)
// position 8-15: right face (x=7, y=7-0)
// position 16-23: back face (y=0, x=7-0)
// position 24-31: left face (x=0, y=0-7)
function setColumnAtPosition(frame, col, position) {
  // Flip the column vertically so letters appear right-side up
  const finalCol = flipColumnVertical(col);

  let mask = 0;
  for (let z = 0; z < 7; z++) {
    if ((finalCol >> z) & 1) mask |= 1 << z;
  }

  if (position >= 0 && position < 8) {
    // Front face: y=7, x=position
    frame[8 * 7 + position] = mask;
  } else if (position >= 8 && position < 16) {
    // Right face: x=7, y=7-(position-8)
    const y = 7 - (position - 8);
    frame[8 * y + 7] = mask;
  } else if (position >= 16 && position < 24) {
    // Back face: y=0, x=7-(position-16)
    const x = 7 - (position - 16);
    frame[8 * 0 + x] = mask;
  } else if (position >= 24 && position < 32) {
    // Left face: x=0, y=position-24
    const y = position - 24;
    frame[8 * y + 0] = mask;
  }
}

// Scroll text continuously around specified number of sides. Returns array of frames.
// sides: number of sides (1-4) to use for scrolling
// direction: 'ltr' (default) or 'rtl' (render columns for right-to-left preview)
export function generateTextFrames(text = '', sides = 1, direction = 'ltr') {
  const t = String(text || '').toUpperCase();
  if (!t) return [];

  // Build column buffer - forward order to match physical cube direction
  const cols = [];

  // Build in forward order (this will make it scroll in the correct direction)
  for (let i = 0; i < t.length; i++) {
    const ch = t[i];
    const glyph = FONT5x7[ch] || FONT5x7[' '];
    cols.push(0x00); // spacing
    // Add columns in forward order
    for (let ci = 0; ci < glyph.length; ci++) {
      cols.push(glyph[ci]);
    }
  }

  const padding = [];
  const buffer = padding.concat(cols).concat(padding);

  // Total positions available based on number of sides
  const positionsPerSide = 8;
  const totalPositions = sides * positionsPerSide;

  const frames = [];

  // Create frames where text flows continuously around the sides
  // We need enough frames to scroll the entire buffer through the visible window
  const numFrames = buffer.length + totalPositions;

  for (let frameIdx = 0; frameIdx < numFrames; frameIdx++) {
    const frame = new Array(64).fill(0x00);

    // For this frame, render columns at each visible position
    for (let pos = 0; pos < totalPositions; pos++) {
      // Reverse the buffer index calculation to change scroll direction
      const bufferIndex = frameIdx + pos - totalPositions;

      if (bufferIndex >= 0 && bufferIndex < buffer.length) {
        const col = buffer[bufferIndex];
        setColumnAtPosition(frame, col, pos);
      }
    }

    frames.push(frame);
  }

  return frames;
}

// Render glyph columns to a specific face with optional thickness
function renderColumnsToFace(glyph, face = 'front', thickness = 1) {
  const frame = new Array(64).fill(0x00);

  for (let cx = 0; cx < Math.min(5, glyph.length); cx++) {
    const col = flipColumnVertical(glyph[cx] || 0);

    // Center the glyph horizontally
    const x = cx + 1; // This centers a 5-wide glyph in 8-wide space

    let mask = 0;
    for (let z = 0; z < 7; z++) {
      if ((col >> z) & 1) {
        mask |= 1 << z;
      }
    }

    if (face === 'front') {
      // Place on front face (y = 7) and optionally one layer back for thickness
      frame[8 * 7 + x] = mask;
      if (thickness > 1) {
        frame[8 * 6 + x] = mask; // One layer back
      }
    }
    // Add other faces if needed
  }

  return frame;
}

// Render a single glyph and produce animated frames
import { rotateZ90 } from './drawHelpers.js';

export function generateGlyphFrames(char = 'A', steps = 4, mode = 'flat') {
  const ch = String(char || ' ').toUpperCase();

  if (mode === '3d') {
    // True 3D center spin: render readable glyph in 3D space using CUBE8x8_FONT
    return generate3DGlyphSpin(ch, steps);
  } else {
    // Flat rotation on front face using standard FONT5x7
    const glyph = FONT5x7[ch] || FONT5x7[' '];
    const base = renderColumnsToFace(glyph, 'front', 2);
    const res = [base];
    let cur = base;
    for (let s = 1; s < steps; s++) {
      cur = rotateZ90(cur);
      res.push(cur.slice());
    }
    return res;
  }
}

function generate3DGlyphSpin(glyph, steps) {
  const frames = [];

  // Use the new CUBE8x8_FONT for optimal 3D display
  const charPattern = CUBE8x8_FONT[glyph.toUpperCase()] || CUBE8x8_FONT[' '];

  const CUBE_SIZE = 8;
  const ACTUAL_WIDTH = charPattern.length; 

  // 1. DYNAMIC HEIGHT CALCULATOR
  // Scans the array values to check if any column uses all 8 vertical bits
  let maxBitRow = 0;
  for (let col = 0; col < ACTUAL_WIDTH; col++) {
    const val = charPattern[col];
    for (let bit = 7; bit >= 0; bit--) {
      if ((val & (1 << bit)) && bit > maxBitRow) {
        maxBitRow = bit;
      }
    }
  }
  // The row height matches the highest active bit + 1 (e.g., bit 7 active = height 8)
  const ACTUAL_HEIGHT = Math.max(7, maxBitRow + 1);

  // Symmetrical centers across the 2D plane
  const centerX = 3.5;
  const centerY = 3.5;
  
  // 2. DYNAMIC VERTICAL ALIGNMENT
  // Safely pins the bottom layer to index 0 if the icon fills all 8 layers
  const charStartY = ACTUAL_HEIGHT >= 8 ? 0 : Math.round(4 - (ACTUAL_HEIGHT / 2));

  // Dynamic horizontal midpoint balancing
  const localCenter = (ACTUAL_WIDTH - 1) / 2;

  // Icons drawn full-height (0-7 rows) get a different vertical orientation
  // in the 3D spin than the narrower letter glyphs -- this list is anything
  // in CUBE8x8_FONT that isn't a letter/number/punctuation character.
  const fullIconKeys = [
    'SMILE', 'SAD', 'WINK', 'HEART', 'SHOCK', 'ANGRY', 'BORED', 'TONGUE',
    'ARROW_UP', 'ARROW_DOWN', 'ARROW_LEFT', 'ARROW_RIGHT',
    'SPADE', 'DIAMOND', 'CLUB',
    'SNOWFLAKE', 'TREE', 'PUMPKIN',
    'GHOST', 'PACMAN', 'INVADER',
  ];
  const isEmoticon = fullIconKeys.includes(String(glyph).toUpperCase());

  for (let step = 0; step < steps; step++) {
    const frame = new Array(64).fill(0x00);
    const angle = (step / steps) * Math.PI * 2;

    for (let col = 0; col < ACTUAL_WIDTH; col++) {
      const columnData = charPattern[col];

      // 3. FIX: Check all layers up to the dynamic character height limit
      for (let row = 0; row < ACTUAL_HEIGHT; row++) {
        if (columnData & (1 << row)) {
          
          const charX = col - localCenter; 
          const charZ = isEmoticon ? row : (ACTUAL_HEIGHT - 1 - row); 

          // Thickness logic loop
          for (let thickness = 0; thickness < 2; thickness++) {
            const charY = thickness - 0.5; 

            // Rotation equations
            const cosAngle = Math.cos(angle);
            const sinAngle = Math.sin(angle);

            const rotatedX = charX * cosAngle - charY * sinAngle;
            const rotatedY = charX * sinAngle + charY * cosAngle;

            // Final coordinate maps
            const cubeX = Math.round(centerX + rotatedX);
            const finalY = Math.round(centerY + rotatedY);
            const cubeZ = charStartY + charZ;

            // Bounds checking
            if (
              cubeX >= 0 &&
              cubeX < CUBE_SIZE &&
              finalY >= 0 &&
              finalY < CUBE_SIZE &&
              cubeZ >= 0 &&
              cubeZ < CUBE_SIZE
            ) {
              const byteIndex = CUBE_SIZE * finalY + cubeX;
              if (byteIndex >= 0 && byteIndex < 64) {
                frame[byteIndex] |= 1 << cubeZ;
              }
            }
          }
        }
      }
    }

    frames.push(frame);
  }

  return frames;
}